version: '3.8'

services:
  discovery-server:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    container_name: discovery-server
    hostname: discovery-server
    ports:
      - "8761:8761"
    networks:
      - bloop-it_sensitives_network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    hostname: api-gateway
    ports:
      - "8080:8080"
    networks:
      - bloop-it_sensitives_network
    depends_on:
      - discovery-server
    environment:
      - eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
#      - EUREKA_SERVER=http://discovery-server:8761/eureka/

  client-request-services:
    build: ./client-request-services
    container_name: client-request-services
    networks:
      - bloop-it_sensitives_network
    depends_on:
      - discovery-server
    environment:
      - eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/

  sensitive-word-service:
    build:
      context: ./sensitive-word-service
      dockerfile: Dockerfile
    container_name: sensitive-word-service
    networks:
      - bloop-it_sensitives_network
    depends_on:
      - discovery-server
      - postgres-server
    environment:
      - eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
#      - SPRING_DATASOURCE_URL= jdbc:sqlserver://mssql-server:1433;createDatabaseIfNotExist=true;databaseName=SensitiveWordsDb;encrypt=true;trustServerCertificate=true;integratedSecurity=true;
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-server:5432/SensitiveWordsDb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Siz@7834

#  mssql-server:
#    image: mcr.microsoft.com/mssql/server
#    container_name: mssql-server
#    networks:
#      - bloop-it_sensitives_network
#    environment:
#      - ACCEPT_EULA=Y
#      - SA_PASSWORD=awes0m3Pa$$w0rd!
#      - MSSQL_PID=Developer
#    ports:
#      - "1433:1433"

  postgres-server:
    image: postgres
    container_name: postgres-server
    networks:
      - bloop-it_sensitives_network
    environment:
      - POSTGRES_DB=SensitiveWordsDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Siz@7834
    ports:
      - "5432:5432"

networks:
  bloop-it_sensitives_network:
    driver: bridge