version: '3.8'

services:
  discovery-server:
    image: sizwencikana/discovery-server:latest
    ports:
      - "8761:8761"
    networks:
      - microservices_network
    deploy:
      resources:
        limits:
          memory: 700M

  api-gateway:
    image: sizwencikana/api-gateway:latest
    depends_on:
      - discovery-server
    ports:
      - "8080:8080"
    networks:
      - microservices_network
    deploy:
      resources:
        limits:
          memory: 700M
    command: sh -c "sleep 40 && java -jar /app/api-gateway-0.0.1-SNAPSHOT.jar"

  client-request-services:
    image: sizwencikana/client-request-service:latest
    ports:
      - "8081:8081"
    networks:
      - microservices_network
    deploy:
      resources:
        limits:
          memory: 700M
    command: sh -c "sleep 40 && java -jar /app/client-request-services-0.0.1-SNAPSHOT.jar"

  sensitive-word-service:
    image: sizwencikana/bloop-sensitive-word-service:latest
    ports:
      - "8082:8082"
    networks:
      - microservices_network
    deploy:
      resources:
        limits:
          memory: 700M
    command: sh -c "sleep 40 && java -jar /app/sensitive-word-service-1.0-SNAPSHOT.jar"

networks:
  microservices_network:
    driver: bridge